# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'work_files_form.ui'
#
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_WorkFilesForm(object):
    def setupUi(self, WorkFilesForm):
        WorkFilesForm.setObjectName("WorkFilesForm")
        WorkFilesForm.resize(823, 644)
        WorkFilesForm.setStyleSheet("")
        self.verticalLayout_8 = QtGui.QVBoxLayout(WorkFilesForm)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.items_title_label_2 = QtGui.QLabel(WorkFilesForm)
        self.items_title_label_2.setMinimumSize(QtCore.QSize(0, 44))
        self.items_title_label_2.setStyleSheet("")
        self.items_title_label_2.setMargin(4)
        self.items_title_label_2.setObjectName("items_title_label_2")
        self.verticalLayout_6.addWidget(self.items_title_label_2)
        self.work_area_frame = QtGui.QFrame(WorkFilesForm)
        self.work_area_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.work_area_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.work_area_frame.setCursor(QtCore.Qt.PointingHandCursor)
        self.work_area_frame.setStyleSheet("#work_area_frame {\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-width: 1px;\n"
"border-color: rgb(32,32,32);\n"
"}")
        self.work_area_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.work_area_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.work_area_frame.setObjectName("work_area_frame")
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.work_area_frame)
        self.verticalLayout_20.setSpacing(6)
        self.verticalLayout_20.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.project_pages = QtGui.QStackedWidget(self.work_area_frame)
        self.project_pages.setLineWidth(0)
        self.project_pages.setObjectName("project_pages")
        self.project_page = QtGui.QWidget()
        self.project_page.setObjectName("project_page")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.project_page)
        self.verticalLayout_10.setSpacing(8)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.project_frame = QtGui.QFrame(self.project_page)
        self.project_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.project_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.project_frame.setObjectName("project_frame")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.project_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.project_label = QtGui.QLabel(self.project_frame)
        self.project_label.setMinimumSize(QtCore.QSize(240, 0))
        self.project_label.setMaximumSize(QtCore.QSize(240, 16777215))
        self.project_label.setStyleSheet("#project_label {\n"
"font-size: 12pt\n"
"}")
        self.project_label.setObjectName("project_label")
        self.verticalLayout_7.addWidget(self.project_label)
        self.project_line = QtGui.QFrame(self.project_frame)
        self.project_line.setMinimumSize(QtCore.QSize(0, 1))
        self.project_line.setMaximumSize(QtCore.QSize(16777215, 1))
        self.project_line.setFrameShadow(QtGui.QFrame.Plain)
        self.project_line.setFrameShape(QtGui.QFrame.HLine)
        self.project_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.project_line.setObjectName("project_line")
        self.verticalLayout_7.addWidget(self.project_line)
        self.project_description = QtGui.QLabel(self.project_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_description.sizePolicy().hasHeightForWidth())
        self.project_description.setSizePolicy(sizePolicy)
        self.project_description.setMinimumSize(QtCore.QSize(240, 0))
        self.project_description.setMaximumSize(QtCore.QSize(240, 16777215))
        self.project_description.setStyleSheet("#project_description {\n"
"font-size: 9pt\n"
"}")
        self.project_description.setText("")
        self.project_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.project_description.setWordWrap(True)
        self.project_description.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.project_description.setObjectName("project_description")
        self.verticalLayout_7.addWidget(self.project_description)
        self.verticalLayout_7.setStretch(2, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.project_thumbnail = QtGui.QLabel(self.project_frame)
        self.project_thumbnail.setMinimumSize(QtCore.QSize(100, 100))
        self.project_thumbnail.setMaximumSize(QtCore.QSize(100, 100))
        self.project_thumbnail.setStyleSheet("#project_thumbnail {\n"
"background-color: rgb(0,0,0,32);\n"
"border-radius: 2px;\n"
"}")
        self.project_thumbnail.setFrameShape(QtGui.QFrame.NoFrame)
        self.project_thumbnail.setLineWidth(0)
        self.project_thumbnail.setText("")
        self.project_thumbnail.setAlignment(QtCore.Qt.AlignCenter)
        self.project_thumbnail.setMargin(0)
        self.project_thumbnail.setIndent(0)
        self.project_thumbnail.setObjectName("project_thumbnail")
        self.verticalLayout_11.addWidget(self.project_thumbnail)
        spacerItem = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout_11)
        self.horizontalLayout_3.setStretch(0, 1)
        self.verticalLayout_10.addWidget(self.project_frame)
        self.entity_pages = QtGui.QStackedWidget(self.project_page)
        self.entity_pages.setStyleSheet("")
        self.entity_pages.setLineWidth(0)
        self.entity_pages.setObjectName("entity_pages")
        self.entity_page = QtGui.QWidget()
        self.entity_page.setObjectName("entity_page")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.entity_page)
        self.verticalLayout_5.setSpacing(8)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.entity_frame = QtGui.QFrame(self.entity_page)
        self.entity_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.entity_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.entity_frame.setObjectName("entity_frame")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.entity_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.entity_label = QtGui.QLabel(self.entity_frame)
        self.entity_label.setMinimumSize(QtCore.QSize(240, 0))
        self.entity_label.setMaximumSize(QtCore.QSize(240, 16777215))
        self.entity_label.setStyleSheet("#entity_label {\n"
"font-size: 12pt\n"
"}")
        self.entity_label.setObjectName("entity_label")
        self.verticalLayout_3.addWidget(self.entity_label)
        self.entity_line = QtGui.QFrame(self.entity_frame)
        self.entity_line.setMinimumSize(QtCore.QSize(0, 1))
        self.entity_line.setMaximumSize(QtCore.QSize(16777215, 1))
        self.entity_line.setFrameShadow(QtGui.QFrame.Plain)
        self.entity_line.setFrameShape(QtGui.QFrame.HLine)
        self.entity_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.entity_line.setObjectName("entity_line")
        self.verticalLayout_3.addWidget(self.entity_line)
        self.entity_description = QtGui.QLabel(self.entity_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entity_description.sizePolicy().hasHeightForWidth())
        self.entity_description.setSizePolicy(sizePolicy)
        self.entity_description.setMinimumSize(QtCore.QSize(240, 0))
        self.entity_description.setMaximumSize(QtCore.QSize(240, 16777215))
        self.entity_description.setStyleSheet("#entity_description {\n"
"font-size: 9pt\n"
"}")
        self.entity_description.setText("")
        self.entity_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.entity_description.setWordWrap(True)
        self.entity_description.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.entity_description.setObjectName("entity_description")
        self.verticalLayout_3.addWidget(self.entity_description)
        self.verticalLayout_3.setStretch(2, 1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.entity_thumbnail = QtGui.QLabel(self.entity_frame)
        self.entity_thumbnail.setMinimumSize(QtCore.QSize(100, 100))
        self.entity_thumbnail.setMaximumSize(QtCore.QSize(100, 100))
        self.entity_thumbnail.setStyleSheet("#entity_thumbnail {\n"
"background-color: rgb(0,0,0,32);\n"
"border-radius: 2px;\n"
"}")
        self.entity_thumbnail.setLineWidth(0)
        self.entity_thumbnail.setText("")
        self.entity_thumbnail.setScaledContents(False)
        self.entity_thumbnail.setAlignment(QtCore.Qt.AlignCenter)
        self.entity_thumbnail.setObjectName("entity_thumbnail")
        self.verticalLayout_4.addWidget(self.entity_thumbnail)
        spacerItem1 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.setStretch(0, 1)
        self.verticalLayout_5.addWidget(self.entity_frame)
        self.task_pages = QtGui.QStackedWidget(self.entity_page)
        self.task_pages.setLineWidth(0)
        self.task_pages.setObjectName("task_pages")
        self.task_page = QtGui.QWidget()
        self.task_page.setObjectName("task_page")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.task_page)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.task_frame = QtGui.QFrame(self.task_page)
        self.task_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.task_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.task_frame.setObjectName("task_frame")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.task_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_21 = QtGui.QVBoxLayout()
        self.verticalLayout_21.setSpacing(6)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.task_label = QtGui.QLabel(self.task_frame)
        self.task_label.setMinimumSize(QtCore.QSize(240, 0))
        self.task_label.setMaximumSize(QtCore.QSize(240, 16777215))
        self.task_label.setStyleSheet("#task_label {\n"
"font-size: 12pt\n"
"}")
        self.task_label.setObjectName("task_label")
        self.verticalLayout_21.addWidget(self.task_label)
        self.task_line = QtGui.QFrame(self.task_frame)
        self.task_line.setMinimumSize(QtCore.QSize(0, 1))
        self.task_line.setMaximumSize(QtCore.QSize(16777215, 1))
        self.task_line.setFrameShadow(QtGui.QFrame.Plain)
        self.task_line.setFrameShape(QtGui.QFrame.HLine)
        self.task_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.task_line.setObjectName("task_line")
        self.verticalLayout_21.addWidget(self.task_line)
        self.task_description = QtGui.QLabel(self.task_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.task_description.sizePolicy().hasHeightForWidth())
        self.task_description.setSizePolicy(sizePolicy)
        self.task_description.setMinimumSize(QtCore.QSize(240, 0))
        self.task_description.setMaximumSize(QtCore.QSize(240, 16777215))
        self.task_description.setStyleSheet("#task_description {\n"
"font-size: 9pt\n"
"}")
        self.task_description.setText("")
        self.task_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.task_description.setWordWrap(True)
        self.task_description.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.task_description.setObjectName("task_description")
        self.verticalLayout_21.addWidget(self.task_description)
        self.verticalLayout_21.setStretch(2, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtGui.QVBoxLayout()
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.task_thumbnail = QtGui.QLabel(self.task_frame)
        self.task_thumbnail.setMinimumSize(QtCore.QSize(100, 100))
        self.task_thumbnail.setMaximumSize(QtCore.QSize(100, 100))
        self.task_thumbnail.setStyleSheet("#task_thumbnail {\n"
"background-color: rgb(0,0,0,32);\n"
"border-radius: 2px;\n"
"}")
        self.task_thumbnail.setFrameShape(QtGui.QFrame.NoFrame)
        self.task_thumbnail.setLineWidth(0)
        self.task_thumbnail.setText("")
        self.task_thumbnail.setAlignment(QtCore.Qt.AlignCenter)
        self.task_thumbnail.setMargin(0)
        self.task_thumbnail.setIndent(0)
        self.task_thumbnail.setObjectName("task_thumbnail")
        self.verticalLayout_22.addWidget(self.task_thumbnail)
        spacerItem2 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_22.addItem(spacerItem2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_22)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_6.addWidget(self.task_frame)
        self.task_pages.addWidget(self.task_page)
        self.no_task_page = QtGui.QWidget()
        self.no_task_page.setObjectName("no_task_page")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.no_task_page)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.no_task_label = QtGui.QLabel(self.no_task_page)
        self.no_task_label.setStyleSheet("#no_task_label {\n"
"font-size: 14pt;\n"
"border-style: dashed;\n"
"border-width: 2px;\n"
"border-radius: 3px;\n"
"}")
        self.no_task_label.setAlignment(QtCore.Qt.AlignCenter)
        self.no_task_label.setObjectName("no_task_label")
        self.horizontalLayout_7.addWidget(self.no_task_label)
        self.task_pages.addWidget(self.no_task_page)
        self.verticalLayout_5.addWidget(self.task_pages)
        self.entity_pages.addWidget(self.entity_page)
        self.no_entity_page = QtGui.QWidget()
        self.no_entity_page.setObjectName("no_entity_page")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.no_entity_page)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.no_entity_label = QtGui.QLabel(self.no_entity_page)
        self.no_entity_label.setStyleSheet("#no_entity_label {\n"
"font-size: 14pt;\n"
"border-style: dashed;\n"
"border-width: 2px;\n"
"border-radius: 3px;\n"
"}")
        self.no_entity_label.setAlignment(QtCore.Qt.AlignCenter)
        self.no_entity_label.setObjectName("no_entity_label")
        self.horizontalLayout_10.addWidget(self.no_entity_label)
        self.entity_pages.addWidget(self.no_entity_page)
        self.verticalLayout_10.addWidget(self.entity_pages)
        self.project_pages.addWidget(self.project_page)
        self.no_project_page = QtGui.QWidget()
        self.no_project_page.setObjectName("no_project_page")
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.no_project_page)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.no_project_label = QtGui.QLabel(self.no_project_page)
        self.no_project_label.setStyleSheet("#no_project_label {\n"
"font-size: 14pt;\n"
"border-style: dashed;\n"
"border-width: 2px;\n"
"border-radius: 3px;\n"
"}")
        self.no_project_label.setAlignment(QtCore.Qt.AlignCenter)
        self.no_project_label.setObjectName("no_project_label")
        self.horizontalLayout_16.addWidget(self.no_project_label)
        self.project_pages.addWidget(self.no_project_page)
        self.verticalLayout_20.addWidget(self.project_pages)
        self.no_change_frame = QtGui.QFrame(self.work_area_frame)
        self.no_change_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.no_change_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.no_change_frame.setObjectName("no_change_frame")
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.no_change_frame)
        self.verticalLayout_19.setSpacing(6)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.no_change_line = QtGui.QFrame(self.no_change_frame)
        self.no_change_line.setMinimumSize(QtCore.QSize(0, 1))
        self.no_change_line.setMaximumSize(QtCore.QSize(16777215, 1))
        self.no_change_line.setStyleSheet("#no_change_line {\n"
"background-color: rgb(32,32,32);\n"
"}")
        self.no_change_line.setFrameShadow(QtGui.QFrame.Plain)
        self.no_change_line.setLineWidth(1)
        self.no_change_line.setMidLineWidth(0)
        self.no_change_line.setFrameShape(QtGui.QFrame.HLine)
        self.no_change_line.setFrameShadow(QtGui.QFrame.Sunken)
        self.no_change_line.setObjectName("no_change_line")
        self.verticalLayout_19.addWidget(self.no_change_line)
        self.no_change_label = QtGui.QLabel(self.no_change_frame)
        self.no_change_label.setStyleSheet("#no_change_label {\n"
"font-size: 9pt\n"
"}")
        self.no_change_label.setIndent(0)
        self.no_change_label.setObjectName("no_change_label")
        self.verticalLayout_19.addWidget(self.no_change_label)
        self.verticalLayout_20.addWidget(self.no_change_frame)
        self.verticalLayout_6.addWidget(self.work_area_frame)
        self.items_title_label_3 = QtGui.QLabel(WorkFilesForm)
        self.items_title_label_3.setMinimumSize(QtCore.QSize(0, 44))
        self.items_title_label_3.setStyleSheet("")
        self.items_title_label_3.setMargin(4)
        self.items_title_label_3.setObjectName("items_title_label_3")
        self.verticalLayout_6.addWidget(self.items_title_label_3)
        self.files_filter_frame = QtGui.QFrame(WorkFilesForm)
        self.files_filter_frame.setStyleSheet("#files_filter_frame {\n"
"border-style: solid;\n"
"border-radius: 2px;\n"
"border-width: 1px;\n"
"border-color: rgb(32,32,32);\n"
"}")
        self.files_filter_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.files_filter_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.files_filter_frame.setObjectName("files_filter_frame")
        self.verticalLayout = QtGui.QVBoxLayout(self.files_filter_frame)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filter_combo = QtGui.QComboBox(self.files_filter_frame)
        self.filter_combo.setMinimumSize(QtCore.QSize(0, 0))
        self.filter_combo.setObjectName("filter_combo")
        self.verticalLayout.addWidget(self.filter_combo)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.show_in_fs_label = QtGui.QLabel(self.files_filter_frame)
        self.show_in_fs_label.setCursor(QtCore.Qt.PointingHandCursor)
        self.show_in_fs_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.show_in_fs_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.show_in_fs_label.setObjectName("show_in_fs_label")
        self.horizontalLayout_8.addWidget(self.show_in_fs_label)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout_6.addWidget(self.files_filter_frame)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.verticalLayout_6.setStretch(4, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.file_list = FileListView(WorkFilesForm)
        self.file_list.setStyleSheet("#file_list {\n"
"background-color: rgb(255, 128, 0);\n"
"}")
        self.file_list.setObjectName("file_list")
        self.horizontalLayout.addWidget(self.file_list)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.new_file_btn = QtGui.QPushButton(WorkFilesForm)
        self.new_file_btn.setMinimumSize(QtCore.QSize(80, 0))
        self.new_file_btn.setObjectName("new_file_btn")
        self.horizontalLayout_2.addWidget(self.new_file_btn)
        self.open_file_btn = QtGui.QPushButton(WorkFilesForm)
        self.open_file_btn.setMinimumSize(QtCore.QSize(80, 0))
        self.open_file_btn.setObjectName("open_file_btn")
        self.horizontalLayout_2.addWidget(self.open_file_btn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)

        self.retranslateUi(WorkFilesForm)
        self.project_pages.setCurrentIndex(0)
        self.entity_pages.setCurrentIndex(0)
        self.task_pages.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(WorkFilesForm)

    def retranslateUi(self, WorkFilesForm):
        WorkFilesForm.setWindowTitle(QtGui.QApplication.translate("WorkFilesForm", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.items_title_label_2.setText(QtGui.QApplication.translate("WorkFilesForm", "<big>Select a Work Area</big>", None, QtGui.QApplication.UnicodeUTF8))
        self.work_area_frame.setToolTip(QtGui.QApplication.translate("WorkFilesForm", "Click to Change Work Area...", None, QtGui.QApplication.UnicodeUTF8))
        self.project_label.setText(QtGui.QApplication.translate("WorkFilesForm", "Project:", None, QtGui.QApplication.UnicodeUTF8))
        self.entity_label.setText(QtGui.QApplication.translate("WorkFilesForm", "Shot:", None, QtGui.QApplication.UnicodeUTF8))
        self.task_label.setText(QtGui.QApplication.translate("WorkFilesForm", "Task:", None, QtGui.QApplication.UnicodeUTF8))
        self.no_task_label.setText(QtGui.QApplication.translate("WorkFilesForm", "Click to Select a Task", None, QtGui.QApplication.UnicodeUTF8))
        self.no_entity_label.setText(QtGui.QApplication.translate("WorkFilesForm", "Click to Select a Work Area", None, QtGui.QApplication.UnicodeUTF8))
        self.no_project_label.setText(QtGui.QApplication.translate("WorkFilesForm", "Click to Select a Work Area", None, QtGui.QApplication.UnicodeUTF8))
        self.no_change_label.setText(QtGui.QApplication.translate("WorkFilesForm", "<html><head/><body><p><span style=\" font-style:italic;\">(Note: The Work Area is locked and cannot be changed)</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.items_title_label_3.setText(QtGui.QApplication.translate("WorkFilesForm", "<big>Choose Which Files to Display</big>", None, QtGui.QApplication.UnicodeUTF8))
        self.filter_combo.setToolTip(QtGui.QApplication.translate("WorkFilesForm", "Choose where to find the list of available files", None, QtGui.QApplication.UnicodeUTF8))
        self.show_in_fs_label.setToolTip(QtGui.QApplication.translate("WorkFilesForm", "Show the selected location in the file system", None, QtGui.QApplication.UnicodeUTF8))
        self.show_in_fs_label.setText(QtGui.QApplication.translate("WorkFilesForm", "<html><head/><body><p><span style=\" text-decoration: underline;\">Show in File System</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.new_file_btn.setToolTip(QtGui.QApplication.translate("WorkFilesForm", "Start a New file in the selected Work Area", None, QtGui.QApplication.UnicodeUTF8))
        self.new_file_btn.setText(QtGui.QApplication.translate("WorkFilesForm", "New File", None, QtGui.QApplication.UnicodeUTF8))
        self.open_file_btn.setToolTip(QtGui.QApplication.translate("WorkFilesForm", "Open the selected file", None, QtGui.QApplication.UnicodeUTF8))
        self.open_file_btn.setText(QtGui.QApplication.translate("WorkFilesForm", "Open File", None, QtGui.QApplication.UnicodeUTF8))

from ..file_list_view import FileListView
from . import resources_rc
